### ISSUE TITLE
Confusion about L_seg for target samples

### ISSUE THREAD

**Issue by tsunghan-wu** [uta-smile/ASSUDA#3]
Dear authors,

Thanks for sharing your excellent works as an ICCV 2021 Oral paper.
After reading paper and source code, I'm a bit confused about the L_seg in Equation 7 for target domain samples.

Specifically, according to the provided source code ([link](https://github.com/uta-smile/ASSUDA/blob/main/main.py#L111-L113)), the loss is defined as a conventional segmentation loss requiring target annotations.
However, as an unsupervised domain adaptation problem, we are not able to acquire such information.
Thus, in my opinion, this loss term should not be used while training.

I would be very grateful if the authors could provide further explanation about this issue.
Looking forward to your reply!

Best,
Tsung-Han Wu

**Comment by viyjy** [comment]
Thanks for your interest in our work.
They are pseudo labels for the target domain, not the real labels.

**Comment by tsunghan-wu** [comment]
Sorry for the late reply. Thanks for your kind reminder. I understand it now.
